version: "3"

services:
  nginx:
    image: nginx:1.16.1-alpine
    ports:
      - 80:80 
      - 443:443
    volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/log:/var/log/nginx
            - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - wordpress
    restart: always


  # WordPress+PHP7.4
  wordpress:
    image: wordpress:php7.4-apache
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
      - ./wordpress-php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - mysql
    restart: always

  # MySQL
  mysql:
    image: mariadb:10.5.8
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always